//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        public int Id { get; set; }
        public Nullable<int> ViajeId { get; set; }
        public string NombrePasajero { get; set; }
        public string CedulaPasajero { get; set; }
        public string TelefonoPasajero { get; set; }
        public string EmailPasajero { get; set; }
        public int AsientoSeleccionado { get; set; }
        public string MetodoPago { get; set; }
        public decimal TotalPagar { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
    
        public virtual Viajes Viajes { get; set; }
    }
}
