//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viajes()
        {
            this.Boletos = new HashSet<Boletos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RutaId { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> ConductorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public System.TimeSpan HoraLlegada { get; set; }
        public decimal Precio { get; set; }
        public int AsientosDisponibles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boletos> Boletos { get; set; }
        public virtual Buses Buses { get; set; }
        public virtual Conductores Conductores { get; set; }
        public virtual Rutas Rutas { get; set; }
    }
}
